NVCC=nvcc

NVCCFLAGS=-lineinfo -DNDEBUG -gencode arch=compute_86,code=sm_86 -Xcompiler -fopenmp --expt-relaxed-constexpr

DEVICES_SCEAN_TARGET=block_scan
DEVICES_SCEAN_SRC=block_scan.cu


MATRIX_ROW_REDUCE_TARGET=matrix_row_reduce
MATRIX_ROW_REDUCE_SRC=matrix_row_reduce.cu

FUSED_ONLINE_SOFTMAX_TOPk_TARGET=fused_online_softmax_topk
FUSED_ONLINE_SOFTMAX_TOPk_SRC=fused_online_softmax_topk.cu

LAYERNORM_TARGET=layernorm
LAYERNORM_SRC=layernorm.cu

INPLACE_DOWN_CAST_TARGET=inplace_down_cast
INPLACE_DOWN_CAST_SRC=inplace_down_cast.cu



all: ${DEVICES_SCEAN_TARGET} ${MATRIX_ROW_REDUCE_TARGET} ${FUSED_ONLINE_SOFTMAX_TOPk_TARGET} ${INPLACE_DOWN_CAST_TARGET} ${LAYERNORM_TARGET}

${FUSED_ONLINE_SOFTMAX_TOPk_TARGET}: ${FUSED_ONLINE_SOFTMAX_TOPk_SRC}
	${NVCC} ${FUSED_ONLINE_SOFTMAX_TOPk_SRC} ${NVCCFLAGS} -o ${FUSED_ONLINE_SOFTMAX_TOPk_TARGET}

${DEVICES_SCEAN_TARGET}: ${DEVICES_SCEAN_SRC}
	${NVCC} ${DEVICES_SCEAN_SRC} ${NVCCFLAGS} -o ${DEVICES_SCEAN_TARGET}

${MATRIX_ROW_REDUCE_TARGET}: ${MATRIX_ROW_REDUCE_SRC}
	${NVCC} ${MATRIX_ROW_REDUCE_SRC} ${NVCCFLAGS} -o ${MATRIX_ROW_REDUCE_TARGET}

${LAYERNORM_TARGET}: ${LAYERNORM_SRC}
	${NVCC} ${LAYERNORM_SRC} ${NVCCFLAGS} -o ${LAYERNORM_TARGET}

${INPLACE_DOWN_CAST_TARGET}: ${INPLACE_DOWN_CAST_SRC}
	${NVCC} ${INPLACE_DOWN_CAST_SRC} ${NVCCFLAGS} -o ${INPLACE_DOWN_CAST_TARGET}

clean:
	rm -f ${DEVICES_SCEAN_TARGET}
	rm -f ${MATRIX_ROW_REDUCE_TARGET}
	rm -f ${FUSED_ONLINE_SOFTMAX_TOPk_TARGET}
	rm -f ${LAYERNORM_TARGET}
	rm -f ${INPLACE_DOWN_CAST_TARGET}